### ISSUE TITLE
Missing Symlinks after deploy 

### ISSUE THREAD

**Issue by bgoudey71** [jahzlariosa/pantheon-symlink-generator#2]
Hi
Trying this out with our site on Pantheon.
I ran the gen in Dev and it worked. Wordfence WAF was running and no error.  When we deployed to test it did not and the symlinks were not in the WP-Content folder. I checked the WP-content folder but did not see any symlinks in there for the files in Dev or Test but it was working.  I swear!
A tech at Pantheon recreated the symlinks in Dev for us which I then committed and deployed to test and it worked.
Very Odd. Wish I took screenshots to help more

Will be testing this on other Pantheon sites next week

**Comment by jahzlariosa** [comment]
Hmm, Ever you experience it again please don't hesitate to open a new issue and add more details.
