### ISSUE TITLE
WP 6 & WF - Rules permissions to Wp-content/wflogs

### ISSUE THREAD

**Issue by bgoudey71** [jahzlariosa/pantheon-symlink-generator#4]
Hi 
Getting an error this week after we updated to WP 6 

Rule Update Failed
No rules were updated. Please verify you have permissions to write to the /wp-content/wflogs directory.

Not sure if this is to do with the generator and sorry if it doesn't just checking into it. Created a ticket with Pantheon and will be doing one with WF as well.

**Comment by orlandoayeras** [comment]
Looks like this is something related to the platform security feature of Pantheon when a site was set into a "Locked" state.

**Comment by bgoudey71** [comment]
Yes sorry, my mistake had nothing to do with Symlink Gen. 
Was clutching at straws
